apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiss-deployment
  labels:
    app: kiss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiss
  template:
    metadata:
      labels:
        app: kiss
    spec:
      containers:
      - name: kiss
        image: kiss:1
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
